# Generated by Django 4.2.23 on 2026-04-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.folders'),
        ),
    ]
