# Generated by Django 5.2.15 on 2026-07-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_folders_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='folder_images'),
        ),
        migrations.AddField(
            model_name='folders',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='folder_thumbnails'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
