# Generated by Django 5.2.15 on 2026-07-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_folders_image_folders_thumbnail_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='folders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
