# Generated by Django 5.2.15 on 2026-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_files_created_at_folders_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='folders',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='files',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='folders',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
